<?php
// This file is part of Moodle - http://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.

defined('MOODLE_INTERNAL') || die();

// Plugin strings
$string['pluginname'] = 'Concept Network';
$string['concept_network'] = 'Concept Network';
$string['concept_network:addinstance'] = 'Add a new Concept Network block';
$string['concept_network:myaddinstance'] = 'Add a new Concept Network block to My page';
$string['concept_network:view'] = 'View own concept network';
$string['concept_network:viewall'] = 'View all students\' concept networks';
$string['concept_network:manage'] = 'Manage concept mappings';

// Block content strings
$string['notincourse'] = 'This block is only available in course pages.';
$string['totalconcepts'] = 'Total concepts: {$a}';
$string['avgmastery'] = 'Average mastery: {$a}%';
$string['viewfullnetwork'] = 'View full network';
$string['regenerate'] = 'Regenerate Network';
$string['nodata'] = 'No learning data available yet. Complete some activities to generate your concept network.';

// Network visualization strings
$string['conceptname'] = 'Concept';
$string['masterylevel'] = 'Mastery Level';
$string['attempts'] = 'Attempts';
$string['avgscore'] = 'Average Score';
$string['relationships'] = 'Relationships';
$string['reltype_prerequisite'] = 'Prerequisite';
$string['reltype_similar'] = 'Similar';
$string['reltype_temporal'] = 'Learned Together';
$string['reltype_difficulty'] = 'Difficulty Related';

// Settings strings
$string['settings_heading'] = 'Concept Network Settings';
$string['weight_cooccurrence'] = 'Co-occurrence Weight';
$string['weight_cooccurrence_desc'] = 'Weight for co-occurrence in relationship strength calculation (0.0 - 1.0)';
$string['weight_temporal'] = 'Temporal Proximity Weight';
$string['weight_temporal_desc'] = 'Weight for temporal proximity in relationship strength calculation (0.0 - 1.0)';
$string['weight_performance'] = 'Performance Correlation Weight';
$string['weight_performance_desc'] = 'Weight for performance correlation in relationship strength calculation (0.0 - 1.0)';
$string['min_relationship_strength'] = 'Minimum Relationship Strength';
$string['min_relationship_strength_desc'] = 'Minimum strength threshold to display a relationship (0.0 - 1.0)';
$string['cache_ttl'] = 'Cache Time-To-Live';
$string['cache_ttl_desc'] = 'How long to cache generated networks (in seconds)';

// Activity mapping strings
$string['managemappings'] = 'Manage Concept Mappings';
$string['addmapping'] = 'Add Concept Mapping';
$string['activityname'] = 'Activity';
$string['conceptname'] = 'Concept Name';
$string['mappingweight'] = 'Weight';
$string['autogenerated'] = 'Auto-generated';
$string['deletemapping'] = 'Delete Mapping';

// Error strings
$string['error_nocapability'] = 'You do not have permission to view this concept network.';
$string['error_invalidstudent'] = 'Invalid student ID.';
$string['error_invalidcourse'] = 'Invalid course ID.';
$string['error_generationfailed'] = 'Failed to generate concept network. Please try again.';
$string['error_noactivities'] = 'No activities found in this course.';

// Privacy strings
$string['privacy:metadata:block_concept_network'] = 'Stores student concept network metadata';
$string['privacy:metadata:block_concept_network:student_id'] = 'The ID of the student';
$string['privacy:metadata:block_concept_network:course_id'] = 'The ID of the course';
$string['privacy:metadata:block_concept_network:network_data'] = 'JSON representation of the student\'s concept network';
$string['privacy:metadata:block_student_concept_progress'] = 'Stores detailed student progress per concept';
$string['privacy:metadata:block_student_concept_progress:student_id'] = 'The ID of the student';
$string['privacy:metadata:block_student_concept_progress:score'] = 'The score achieved';
$string['privacy:metadata:block_student_concept_progress:timestamp'] = 'When the activity was completed';
