<?php
// This file is part of Moodle - http://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.

defined('MOODLE_INTERNAL') || die();

// 플러그인 문자열
$string['pluginname'] = '개념 연결망';
$string['concept_network'] = '개념 연결망';
$string['concept_network:addinstance'] = '새 개념 연결망 블록 추가';
$string['concept_network:myaddinstance'] = '내 페이지에 새 개념 연결망 블록 추가';
$string['concept_network:view'] = '자신의 개념 연결망 보기';
$string['concept_network:viewall'] = '모든 학생의 개념 연결망 보기';
$string['concept_network:manage'] = '개념 매핑 관리';

// 블록 콘텐츠 문자열
$string['notincourse'] = '이 블록은 코스 페이지에서만 사용할 수 있습니다.';
$string['totalconcepts'] = '전체 개념: {$a}개';
$string['avgmastery'] = '평균 숙달도: {$a}%';
$string['viewfullnetwork'] = '전체 네트워크 보기';
$string['regenerate'] = '네트워크 재생성';
$string['nodata'] = '아직 학습 데이터가 없습니다. 활동을 완료하면 개념 연결망이 생성됩니다.';

// 네트워크 시각화 문자열
$string['conceptname'] = '개념';
$string['masterylevel'] = '숙달 수준';
$string['attempts'] = '시도 횟수';
$string['avgscore'] = '평균 점수';
$string['relationships'] = '관계';
$string['reltype_prerequisite'] = '선행 학습';
$string['reltype_similar'] = '유사';
$string['reltype_temporal'] = '함께 학습';
$string['reltype_difficulty'] = '난이도 관련';

// 설정 문자열
$string['settings_heading'] = '개념 연결망 설정';
$string['weight_cooccurrence'] = '동시 출현 가중치';
$string['weight_cooccurrence_desc'] = '관계 강도 계산에서 동시 출현의 가중치 (0.0 - 1.0)';
$string['weight_temporal'] = '시간적 근접성 가중치';
$string['weight_temporal_desc'] = '관계 강도 계산에서 시간적 근접성의 가중치 (0.0 - 1.0)';
$string['weight_performance'] = '성과 상관관계 가중치';
$string['weight_performance_desc'] = '관계 강도 계산에서 성과 상관관계의 가중치 (0.0 - 1.0)';
$string['min_relationship_strength'] = '최소 관계 강도';
$string['min_relationship_strength_desc'] = '관계를 표시하기 위한 최소 강도 임계값 (0.0 - 1.0)';
$string['cache_ttl'] = '캐시 유지 시간';
$string['cache_ttl_desc'] = '생성된 네트워크를 캐시하는 시간 (초)';

// 활동 매핑 문자열
$string['managemappings'] = '개념 매핑 관리';
$string['addmapping'] = '개념 매핑 추가';
$string['activityname'] = '활동';
$string['conceptname'] = '개념 이름';
$string['mappingweight'] = '가중치';
$string['autogenerated'] = '자동 생성됨';
$string['deletemapping'] = '매핑 삭제';

// 오류 문자열
$string['error_nocapability'] = '이 개념 연결망을 볼 권한이 없습니다.';
$string['error_invalidstudent'] = '유효하지 않은 학생 ID입니다.';
$string['error_invalidcourse'] = '유효하지 않은 코스 ID입니다.';
$string['error_generationfailed'] = '개념 연결망 생성에 실패했습니다. 다시 시도해주세요.';
$string['error_noactivities'] = '이 코스에서 활동을 찾을 수 없습니다.';

// 개인정보 문자열
$string['privacy:metadata:block_concept_network'] = '학생 개념 연결망 메타데이터 저장';
$string['privacy:metadata:block_concept_network:student_id'] = '학생 ID';
$string['privacy:metadata:block_concept_network:course_id'] = '코스 ID';
$string['privacy:metadata:block_concept_network:network_data'] = '학생 개념 연결망의 JSON 표현';
$string['privacy:metadata:block_student_concept_progress'] = '개념별 학생 진행도 상세 정보 저장';
$string['privacy:metadata:block_student_concept_progress:student_id'] = '학생 ID';
$string['privacy:metadata:block_student_concept_progress:score'] = '획득한 점수';
$string['privacy:metadata:block_student_concept_progress:timestamp'] = '활동 완료 시간';
