#!/bin/bash

# Log Focus App - Installation Script
# For Ubuntu/Debian with Apache, MySQL 5.7, PHP 7.1.9

echo "=========================================="
echo "Log Focus App - Installation Script"
echo "=========================================="
echo ""

# Check if running as root
if [ "$EUID" -ne 0 ]; then
    echo "Please run as root or with sudo"
    exit 1
fi

# Variables
DB_NAME="log_focus_app"
DB_USER="logfocus"
DB_PASS=$(openssl rand -base64 12)
WEB_ROOT="/var/www/html/log-focus-app"

echo "Step 1: Checking dependencies..."

# Check PHP
if ! command -v php &> /dev/null; then
    echo "Error: PHP is not installed"
    exit 1
fi

PHP_VERSION=$(php -v | head -n 1 | cut -d ' ' -f 2 | cut -d '.' -f 1,2)
echo "PHP version: $PHP_VERSION"

# Check MySQL
if ! command -v mysql &> /dev/null; then
    echo "Error: MySQL is not installed"
    exit 1
fi

echo "Dependencies check passed!"
echo ""

echo "Step 2: Creating database..."

# Create database and user
mysql -u root -p <<MYSQL_SCRIPT
CREATE DATABASE IF NOT EXISTS ${DB_NAME} CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS '${DB_USER}'@'localhost' IDENTIFIED BY '${DB_PASS}';
GRANT ALL PRIVILEGES ON ${DB_NAME}.* TO '${DB_USER}'@'localhost';
FLUSH PRIVILEGES;
MYSQL_SCRIPT

if [ $? -eq 0 ]; then
    echo "Database created successfully!"
else
    echo "Error creating database"
    exit 1
fi

# Import schema
mysql -u root -p ${DB_NAME} < database/schema.sql

if [ $? -eq 0 ]; then
    echo "Database schema imported successfully!"
else
    echo "Error importing schema"
    exit 1
fi

echo ""
echo "Step 3: Copying files..."

# Create web directory if doesn't exist
if [ ! -d "$WEB_ROOT" ]; then
    mkdir -p "$WEB_ROOT"
fi

# Copy files
cp -r ./* "$WEB_ROOT/"

if [ $? -eq 0 ]; then
    echo "Files copied successfully!"
else
    echo "Error copying files"
    exit 1
fi

echo ""
echo "Step 4: Setting permissions..."

# Set ownership
chown -R www-data:www-data "$WEB_ROOT"

# Set directory permissions
find "$WEB_ROOT" -type d -exec chmod 755 {} \;

# Set file permissions
find "$WEB_ROOT" -type f -exec chmod 644 {} \;

echo "Permissions set successfully!"
echo ""

echo "Step 5: Updating configuration..."

# Update database config
cat > "$WEB_ROOT/config/database.php" <<EOF
<?php
/**
 * Database Configuration
 * Auto-generated by installation script
 */

define('DB_HOST', 'localhost');
define('DB_NAME', '${DB_NAME}');
define('DB_USER', '${DB_USER}');
define('DB_PASS', '${DB_PASS}');
define('DB_CHARSET', 'utf8mb4');

class Database {
    private static \$instance = null;
    private \$connection;

    private function __construct() {
        try {
            \$dsn = "mysql:host=" . DB_HOST . ";dbname=" . DB_NAME . ";charset=" . DB_CHARSET;
            \$options = [
                PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
                PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,
                PDO::ATTR_EMULATE_PREPARES => false,
            ];

            \$this->connection = new PDO(\$dsn, DB_USER, DB_PASS, \$options);
        } catch (PDOException \$e) {
            error_log("Database connection failed: " . \$e->getMessage());
            throw new Exception("Database connection failed");
        }
    }

    public static function getInstance() {
        if (self::\$instance === null) {
            self::\$instance = new self();
        }
        return self::\$instance;
    }

    public function getConnection() {
        return \$this->connection;
    }

    private function __clone() {}

    public function __wakeup() {
        throw new Exception("Cannot unserialize singleton");
    }
}
EOF

echo "Configuration updated!"
echo ""

echo "Step 6: Enabling Apache modules..."

# Enable required Apache modules
a2enmod rewrite
a2enmod headers
a2enmod expires
a2enmod deflate

# Restart Apache
systemctl restart apache2

echo "Apache configured!"
echo ""

echo "=========================================="
echo "Installation Complete!"
echo "=========================================="
echo ""
echo "Database Credentials (SAVE THESE!):"
echo "-----------------------------------"
echo "Database Name: ${DB_NAME}"
echo "Database User: ${DB_USER}"
echo "Database Password: ${DB_PASS}"
echo ""
echo "Next Steps:"
echo "1. Configure Moodle connection in: $WEB_ROOT/config/moodle.php"
echo "2. Access the app at: http://localhost/log-focus-app/public/"
echo ""
echo "For more information, see README.md"
echo ""
