#!/bin/bash

# Metaphor Log Installation Script
# For Linux/macOS with Apache/MySQL

echo "🌳 Metaphor Log 설치 스크립트"
echo "================================"
echo ""

# Color codes
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Check if running as root
if [ "$EUID" -ne 0 ]; then
    echo -e "${YELLOW}⚠️  이 스크립트는 root 권한이 필요할 수 있습니다.${NC}"
fi

# Check PHP version
echo "1️⃣  PHP 버전 확인 중..."
PHP_VERSION=$(php -v | head -n 1 | cut -d " " -f 2 | cut -d "." -f 1,2)
if (( $(echo "$PHP_VERSION >= 7.1" | bc -l) )); then
    echo -e "${GREEN}✅ PHP $PHP_VERSION 설치됨${NC}"
else
    echo -e "${RED}❌ PHP 7.1 이상이 필요합니다. 현재: $PHP_VERSION${NC}"
    exit 1
fi

# Check MySQL
echo "2️⃣  MySQL 확인 중..."
if command -v mysql &> /dev/null; then
    MYSQL_VERSION=$(mysql -V | cut -d " " -f 6 | cut -d "," -f 1)
    echo -e "${GREEN}✅ MySQL $MYSQL_VERSION 설치됨${NC}"
else
    echo -e "${RED}❌ MySQL이 설치되지 않았습니다.${NC}"
    exit 1
fi

# Database setup
echo ""
echo "3️⃣  데이터베이스 설정"
echo "================================"
read -p "MySQL root 비밀번호 입력: " -s MYSQL_ROOT_PASS
echo ""

# Create database
echo "데이터베이스 생성 중..."
mysql -u root -p"$MYSQL_ROOT_PASS" < database/schema.sql

if [ $? -eq 0 ]; then
    echo -e "${GREEN}✅ 데이터베이스 생성 완료${NC}"
else
    echo -e "${RED}❌ 데이터베이스 생성 실패${NC}"
    exit 1
fi

# Create config file
echo ""
echo "4️⃣  설정 파일 생성"
echo "================================"
read -p "데이터베이스 사용자명 (기본: root): " DB_USER
DB_USER=${DB_USER:-root}

read -p "데이터베이스 비밀번호: " -s DB_PASS
echo ""

read -p "Moodle URL (예: http://localhost/moodle): " MOODLE_URL
read -p "Moodle 토큰 (없으면 엔터): " MOODLE_TOKEN

# Backup existing config
if [ -f "api/config.php" ]; then
    cp api/config.php api/config.php.backup
    echo -e "${YELLOW}⚠️  기존 설정 파일 백업됨: api/config.php.backup${NC}"
fi

# Create new config
cat > api/config.php << EOF
<?php
/**
 * Metaphor Log - Configuration File
 * Generated by install script
 */

error_reporting(E_ALL);
ini_set('display_errors', 1);

// Database configuration
define('DB_HOST', 'localhost');
define('DB_NAME', 'metaphor_log');
define('DB_USER', '$DB_USER');
define('DB_PASS', '$DB_PASS');
define('DB_CHARSET', 'utf8mb4');

// Moodle integration settings
define('MOODLE_URL', '$MOODLE_URL');
define('MOODLE_TOKEN', '$MOODLE_TOKEN');

// Application settings
define('APP_NAME', 'Metaphor Log');
define('APP_VERSION', '1.0.0');
define('TIMEZONE', 'Asia/Seoul');

// Smartphone viewport settings
define('SMARTPHONE_WIDTH', 375);
define('SMARTPHONE_HEIGHT', 667);

// CORS settings
header('Access-Control-Allow-Origin: *');
header('Access-Control-Allow-Methods: GET, POST, PUT, DELETE, OPTIONS');
header('Access-Control-Allow-Headers: Content-Type, Authorization');
header('Content-Type: application/json; charset=utf-8');

// Timezone
date_default_timezone_set(TIMEZONE);

// Session configuration
if (session_status() === PHP_SESSION_NONE) {
    session_start();
}
EOF

echo -e "${GREEN}✅ 설정 파일 생성 완료${NC}"

# Set permissions
echo ""
echo "5️⃣  권한 설정"
echo "================================"
chmod 755 .
chmod 644 public/*
chmod 755 api/
chmod 600 api/config.php

echo -e "${GREEN}✅ 권한 설정 완료${NC}"

# Test installation
echo ""
echo "6️⃣  설치 테스트"
echo "================================"

# Test database connection
php -r "
require_once 'api/db.php';
try {
    \$db = getDB();
    echo '✅ 데이터베이스 연결 성공' . PHP_EOL;
} catch (Exception \$e) {
    echo '❌ 데이터베이스 연결 실패: ' . \$e->getMessage() . PHP_EOL;
}
"

# Print completion message
echo ""
echo "================================"
echo -e "${GREEN}🎉 설치 완료!${NC}"
echo "================================"
echo ""
echo "다음 URL에서 앱에 접속할 수 있습니다:"
echo ""
echo "  http://localhost/metaphor-log-app/public/"
echo ""
echo "또는 웹서버 설정에 따라:"
echo ""
echo "  http://your-domain.com/metaphor-log-app/public/"
echo ""
echo "📚 자세한 사용법은 README.md를 참고하세요."
echo ""
